FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10-1179

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/

RUN microdnf install -y python39 && \
    pip3 install --no-cache-dir -r requirements.txt

COPY . /usr/src/app/

CMD ["./pr_tests/pr_tests.sh"]
