FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5-1742914212

WORKDIR /usr/src/app

COPY Pipfile.lock /usr/src/app/

RUN microdnf install --nodocs -y python39 pip xmlsec1
RUN pip3 install --upgrade pip && pip3 install micropipenv && micropipenv install

COPY . /usr/src/app/

CMD ["./pr_tests/pr_tests.sh"]
