# Set the number of parallel processes for Nginx.
worker_processes 1;

# We are not interested in storing the "pid" of the Nginx process anywhere.
pid /dev/null;

# Set a maximum of simultaneous connections per worker.
events {
    worker_connections 1024;
}

# Any errors should be sent to "stderr".
error_log stderr info;

http {
    # Include the default mime types that the server can understand, and fall
    # back to a "binary" or "octet-stream" for when the mime type is not
    # recognized.
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Log requests to "stdout" with our custom format.
    access_log  /dev/stdout main;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" '
                      '"$host" ($http_x_forwarded_host)';

    # Drop idle connections after a fixed time.
    keepalive_timeout 65;

    # Enable GZIP compression for the requests.
    gzip on;

    # Disable checking request's body size.
    client_max_body_size 0;

    # Include our custom configuration for the server.
    include /etc/nginx/api_gateway.conf;
}
