#!/bin/bash

# you will need to ensure you are logged in to be able to push to the OpenShift registry:
# `docker login -u <user> -p <token> registry.insights-dev.openshift.com:443`

ENV=$1
SUPPORTED_ENV_MSG="Currently supported environments: [ci]"

[ -z "$ENV" ] && echo "Please specify an environment. ${SUPPORTED_ENV_MSG}" && exit 1

if [ "$ENV" == "ci" ]; then
  echo "Deploying to turnpike-ci..."
  docker tag turnpike_nginx registry.insights-dev.openshift.com:443/turnpike-ci/turnpike_nginx:latest
  docker push registry.insights-dev.openshift.com:443/turnpike-ci/turnpike_nginx:latest

  docker tag turnpike_web registry.insights-dev.openshift.com:443/turnpike-ci/turnpike_web:latest
  docker push registry.insights-dev.openshift.com:443/turnpike-ci/turnpike_web:latest
  exit 0
fi

echo ${SUPPORTED_ENV_MSG} && exit 1
