@startuml turnpike-mtls

participant "Service Account w/ x509 client cert" as service_account
box "console.redhat.com"
participant "mTLS Gateway" as gateway
participant Nginx
participant "Policy Service" as policy_service
participant Origin
end box

service_account -> gateway: GET /api/turnpike/identity
note right: Gateway verifies client cert
gateway -> Nginx: GET /api/turnpike/identity
note right: trusted cert confirmed, x-rh-certauth-{subject,issuer} set
Nginx -> policy_service: GET /auth
note left: Nginx asks the Policy Service to authz the cert's subject/issuer
policy_service -> Nginx: 200 Authorized
note right: authorized cert confirmed, X-Rh-Identity set
Nginx -> Origin: /api/turnpike/identity
note left: With X-Rh-Identity header
Origin -> Nginx: 200 OK
Nginx -> service_account: 200 OK

@enduml
