@startuml turnpike-oidc-flow

participant "RH associate or service" as rh_associate_service

box "console.redhat.com"
participant "Nginx" as nginx
participant "Policy service" as policy_service
participant "Service" as service
end box

participant "Red Hat SSO" as red_hat_sso

rh_associate_service -> red_hat_sso: GET /token
note left: The associate or the service requests a token with a service account.
red_hat_sso -> rh_associate_service: Sends the token
rh_associate_service -> rh_associate_service: Does not use the token for a while.
rh_associate_service -> nginx: GET /api/some/service
note left: Sends the token in the request
nginx -> policy_service: GET /auth
note left: Nginx asks the Policy Service to authn/authz
policy_service -> red_hat_sso: Request SSO's JWT signing certificates
red_hat_sso -> policy_service: Send JWKS certificates
policy_service -> policy_service: Verify the token's signature, issuer, scopes and expiration date.
policy_service -> nginx: 401 Unauthorized
note right: The token is expired!
nginx -> rh_associate_service: 401 Unauthorized

rh_associate_service -> red_hat_sso: GET /token
red_hat_sso -> rh_associate_service: Sends the token
rh_associate_service -> nginx: GET /api/some/service
nginx -> policy_service: GET /auth
policy_service -> policy_service: Grabs the JWKS certificates from the cache.
policy_service -> policy_service: Verify the token's signature, issuer, scopes and expiration date.
policy_service -> nginx: 200 OK
note right: The token is valid
nginx -> service: GET /api/some/service
note left: Sends the "x-rh-identity" header in the request.
service -> rh_associate_service: Sends a corresponding response.

@enduml
